### ISSUE TITLE
Append data to existing file

### ISSUE THREAD

**Issue by kalihos** [mapbox/dbf#17]
Hi.

Is it possible to append data (instead of replacing the old file) to an existing DBF file? I tried to use fs methods such appendFileSync or writeSync instead of writeFileSync; and the file updates its date and size, but I can't see new data... only the first registers I added using writeSync.

Thank you very much.

**Comment by tmcw** [comment]
Hi,

Sorry, this is out of scope for this module. Happy to accept a PR that implements this functionality, but supporting append as well as write-once would make this much more complex to maintain. Since this an old and arcane format, I'm going to keep things (that I implement for it) simple.

- Tom
